### ISSUE TITLE
Intrinsic reward coefficient

### ISSUE THREAD

**Issue by initial-h** [beanie00/LESSON#2]
Hi,

I find the Intrinsic reward coefficient is set to a pretty small value, like 0.01 and 0.001. Does this mean the intrinsic reward has a tiny contibute to the learning?

Thanks.

**Comment by beanie00** [comment]
Since the intrinsic reward is cumulative, intrinsic reward with these coefficients can still noticeably affect learning. Depending on the learning objective and environmental characteristics, you can adjust these coefficients to bigger values.

Thank you.
