### ISSUE TITLE
Temperature parameter (tau)

### ISSUE THREAD

**Issue by manuel-delverme** [beanie00/LESSON#3]
In the appendix (table 1) you mention a task dependent parameter  "Temperature" but there is no "tau" or "temperature" in the code, only `softmax_ww`.

Is this the parameter you tuned?

The default parameter is 50 which is not in the paper range, would it be `softmax_ww = 1/tau`?

**Comment by beanie00** [comment]
Yes, you are right! `softmax_ww` is `1/tau`.
