### ISSUE TITLE
Clipping inducing bias

### ISSUE THREAD

**Issue by manuel-delverme** [beanie00/LESSON#4]
https://github.com/beanie00/LESSON/blob/7f0fd515e3961b79719bf08be6b19b6d673bd2af/rl_algorithm/common/option_model.py#L21

The clip in the softmax call makes the probabilities have a sum != 1, this means that later the sampling will be biased

https://github.com/beanie00/LESSON/blob/7f0fd515e3961b79719bf08be6b19b6d673bd2af/rl_algorithm/common/option_model.py#L131-L138

For low temperatures `1/ww` it's likely that many of the probabilities go to 0 and get bumped up to 0.05, with 4 actions if you have 3 of them to zero, you get sums up to ~1.15

[1, 0, 0, 0], becomes [0.95, 0.05, 0.05, 0.05] but the sampling will only consider the first two (because np.random.rand only goes as high as 0.999..) so the distribution becomes equivalent to [0.95, 0.05, 0.00, 0.00].

My suggestion is either re-normalize the clipped probability or just normalize after the clipping.

Also consider using a implementation that subtract the max to avoid numerical issues that could come from extreme Q or `ww` parameters.

**Comment by beanie00** [comment]
Thank you for pointing out. Strictly speaking, what you suggested is more accurate. However, the purpose of the effect of clipping is to prevent it from being too bound to just one option. By allowing the choice of any option and giving the opportunity to select new options, learning can change the overall probability distribution, which seems to be why it works well empirically. If the environment changes, it might be necessary to define it more rigorously.
